### ISSUE TITLE
Inquiry on the practical impact of polling for text

### ISSUE THREAD

**Issue by jugglinmike** [guidepup/guidepup#79]
Hi there! I'm a contributor to [the ARIA-AT project](https://aria-at.w3.org/) exploring web application testing, and I'd like to learn about folks' experience writing web application tests for VoiceOver using GuidePup.

Specifically, I'm looking to understand the practical impact of [using VoiceOver's "last phrase" AppleScript interface](https://github.com/guidepup/guidepup/blob/9adc433aacd43ab978fe1500420f29983d9fce5c/src/macOS/VoiceOver/lastSpokenPhrase.ts). ARIA-AT [rules out the use of polling](https://github.com/w3c/at-driver/issues/32) in order to make claims about the correctness of ATs. We’re curious if these same concerns affect web app testing.

Can you share any feedback on this? Have you ever run into problems or have any GuidePup users reported problems that might stem from polling (e.g. flakiness, false positives, false negatives, inefficiency, etc.)? Thanks for reading and considering sharing your experience.

**Comment by jlp-craigmorten** [comment]
Hey @jugglinmike 👋 

Really sorry for the slow reply 😅 

Your points in https://github.com/w3c/at-driver/issues/32 summarise the caveats well where I have encountered each issue in both building and using this package. I'll try to elaborate on your points with just some additional thoughts as I agree with everything you described.

## Missing vocalizations due to rapid dispatch

Live regions - interruptions somewhat highlight the race conditions.

The "last phrase" interface returns what is actively being spoken / was last spoken, and thus either flakiness or slowness is tied to VoiceOver's speed of narrating text. In cases where VoiceOver has additional "hints" that are announced following an element's role, accName, etc., long accNames can make the process very slow as one has to wait until the first snippet is announced and then the second. This requires you to not only poll, but also handle change detection - the only solution being to poll fast and frequent (so you don't miss anything short), and have a very high "settled" poll count to be satisfied there isn't more output to come. This makes things quite slow, prompting issues to be raised r.e. speed - see https://github.com/guidepup/guidepup/issues/62.

Configuring the `SCRCategories_SCRCategorySystemWide_SCRSpeechLanguages_default_SCRSpeechComponentSettings_SCRRateAsPercent` and `SCRContextualHelpDelayInSeconds` values can make things faster, but I've found the "last phrase" isn't performant enough to guarantee you'll get all output at max speed, leading to flakiness.

Example multi-part output:

- "link, New Issue"
- "You are currently on a link. To click this link, press Control-Option-Space"

## Missing vocalizations due to repeated content

This is somewhat mitigated in this project by forcing each command passed to VoiceOver to not only be queued behind the previous command, but also behind the "last phrase" logic. This means if you have genuine repeated content it can still be announced.

One case where this may fail is again live regions where we may not be able to distinguish between the last phrase from the item in the virtual cursor vs something interrupting... but these don't typically overlap as live regions not tend to announce the likes of roles IIRC.

I haven't encountered this issue using this project since the queuing logic was implemented.

**Comment by jugglinmike** [comment]
Wow, that's really helpful context for our work. Thanks a ton for taking the time to write it up, @jlp-craigmorten, I really appreciate it!
